import { Inter } from "next/font/google";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import { ThemeProvider as NextThemesProvider } from "next-themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "SummarizerX",
  description: "Generated by create next app",
  image: "/take-note.png",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Theme and UI Providers */}
        <NextThemesProvider attribute="class" defaultTheme="dark">
          <NextUIProvider>
            {children}
          </NextUIProvider>
        </NextThemesProvider>
      </body>
    </html>
  );
}
